src/components/AugmentingResponses.js
src/components/SidebarList.js
src/styles.css

Callback requests were being passed to `swagger2har` along with regular spec requests, but callbacks are not supported by the way that swagger2har looks up the request in the swagger object. This bypasses the swagger2har and code snippets steps for callbacks, so their documentation can render without crashing.
Demo

fix(callbacks) fix error during callback render [TDX-1542]

---

package.json
src/components/Layout.js
src/index.js
src/styles.css
webpack.config.js

This PR is to ensure the styles present in `kong-portal-templates` are coming from the upstream theme, so that further CSS changes to the theme can easily flow directly from `swagger-ui-kong-theme`.
- Removes the bundling of CSS in JS from webpack
- Adds `npm run copy-styles` command that puts the `src/styles.css` into a sibling `kong-portal-templates` repo. You have to update the `swagger-ui-kong-theme.<hash>.css` in `spec-renderer.html` to include the updated styles
- Brings all styles that were not present from `kong-portal-templates` `swagger-ui-kong-theme.css` into `src/styles.css`

chore(style) sync styles with kong-portal-templates

---

src/styles.css

We are adding an `oas-version` class to the small that's being used for the OAS version - this adds the necessary colors to solve the contrast issue.

chore: update greens and add styling for oas version label

---

src/containers/Filter.js
src/index.js

This PR adds an `aria-label` attribute to the `FilterContainer` component.

fix: add aria-label to filter by tag input (TDX-1888)

---

src/components/ModelCollapse.js
src/components/Models.js
src/components/OperationTag.js
src/index.js

This PR fixes the issue with the `OperationTag`  not focusing on the right elements. It now focuses on the entire header element, and toggles on keypress / click. Also renames some functions in other files.
@Mierenga I added the `aria-expanded` attribute on the containing `div` instead, as I think that makes more sense semantically (since the div is being collapsed / expanded, not the header).

fix: make entire operation-tag collapsible, rename some functions (TDX-1887)

---

src/components/SidebarList.js
src/styles.css

https://user-images.githubusercontent.com/40131297/162846820-2fa8ea30-6b1b-40b2-ac24-eeb7533836db.mov
Previously, focus would get stuck on the sidebar menu when using voice control to expand one of the menu items. This was caused due to the `role="menuitem"`, so those were removed. `role="button"` isn't allowed to be used on an `<li>` tag, so I wrapped the contents in a div and applied the listeners + role on the div. Result is in the above label - functionally and visually looks the same, but works with voice control

fix: refactor sidebar list to remove roles (TDX-1894)

---

src/components/TryItOutButton.js
src/index.js

The issue was that the buttons weren't descriptive enough - this adds a description that voice over will now read out when you are focused on the button.

fix: add aria descriptions to try it out button

---

src/components/OperationTag.js
src/components/TryItOutButton.js

Changing location of `aria-expanded` and usage of `aria-label` instead of `aria-description`

chore: minor fixes to a11y changes

---

src/components/DeepLink.js
src/components/OperationSummaryPath.js
src/components/OperationTag.js
src/index.js
src/styles.css

This PR adds an `aria-expanded` attribute, as well as an SVG to indicate the section is collapsible.

feat: improve op method accessibility (TDX-2256)

---

src/styles.css

This CSS change targets the blocks where there is a deprecated path.

style: add additional targeting for deprecated styles

---

package.json
yarn.lock

This bumps the version of `react-apiembed` to include accessibility updates to the `CodeSnippetWidget`
- You can now navigate through the different snippets with arrow keys.
- Allows you to focus either the content or the tablist.

chore: bump version of react-apiembed

---

src/components/AugmentingInfo.js
src/styles.css

This PR adds a class to the view spec button so that targeting is simpler when closing the spec modal. In addition, some styles are added in order to improve accessibility. Previously, the outline was removed from buttons so you would not be able to tell if you were focused on them or not.

chore: add class to view spec button + styles (TDX-2350)

---

src/components/ParameterRow.js
src/components/custom/ParameterRowError.js

…eters
^^ shows query param display
^^ shows path error display

feat(try-it-out): add more details to inline error messages for param… [TDX-2351]

---

src/components/ParameterRow.js
src/components/custom/ParameterRowError.js
src/styles.css

Round 2 without console errors:
[Loom demo](https://www.loom.com/share/0c45191208bb4958b7b302e17a4d9d04)
Would love to see one with multiple errors but not sure how that'd play out.

feat(try-it-out): add more details to inline error messages

---

src/components/OperationTag.js
src/styles.css

The accessibility around this title was unclear. Since there's already a button functionality wrapped around this container, the link was replaced with a `div` - meaning that it should not need any `aria` properties to describe it, nor should it need a title attribute. Visually - they should look the exact same
Before
After

refactor: use a div instead of link (TDX-2382) (TDX-2383)

---

src/components/Collapse.js
src/components/Models.js
src/components/OperationTag.js
src/index.js
src/styles.css

replaces with more semantic elements and updates stylings.

fix(a11y): removes overusage of h1 tags

---

src/components/ContentType.js

This PR fixes a bug when `contentTypes` is passed to `<ContentType>` as one of `ImPropTypes.list`, `ImPropTypes.set`, `ImPropTypes.seq`. Related ticket: [FTI-4059](https://konghq.atlassian.net/browse/FTI-4059).

fix(content-type): `contentTypes` supports map-like data [FTI-4059]

---

src/components/ModelCollapse.js
src/components/Models.js
src/components/SidebarList.js

Small a11y improvements 
- Updated the `aria-pressed` attribute to be `aria-expanded` instead, since they were collapsible.
- Added to the sidebar menu, as it was previously missing the attribute.

chore(a11y): change pressed to expanded attributes (TDX-2579)(TDX-2578)

---

package.json
src/components/auth/authorization-popup.js
yarn.lock

Uses a `FocusTrap` library (let me know if others disagree with this usage). Checked and it doesn't look like there are any vulnerabilities with this package.
In addition to adding this package to trap focus, made an improvement on the closing of the modal with `Escape` keypress. This change adds a listener to the document when this component is mounted, and removes the listener when unmounting. This will prevent any issues with the listener colliding with any of the listeners on the focused elements inside of the modal.
https://user-images.githubusercontent.com/40131297/198421118-4dd08dbd-73c5-4eb2-90aa-1d80290fe9c5.mov

feat: trap focus inside auth modal when open (TDX-2576)

---

src/components/DeepLink.js
src/components/ModelCollapse.js
src/components/Models.js
src/components/OperationTag.js
src/components/SidebarList.js
src/components/custom/ParameterRowError.js

Various improvements applied (DWP mentioned in their call that some buttons announce their current state, but don't announce what it'll do e.g. expand if you're already collapsed)

chore: minor a11y label adjustments

---

src/helpers/helpers.js
yarn.lock

Bumps packages that have potential prototype pollution vulnerabilities, and also removed the usage of `Object.assign`

chore: remove usage of object.assign and bump packages [TDX-2680]

---

package.json
yarn.lock

Updates `react-apiembed` and `swagger2har` as those packages have been resolved for prototype pollution.

chore: update packages to resolve prototype pollution

---

package.json
src/styles/_form.scss
src/styles/main.scss

This PR fixes the authorize modal's checkboxes so they are now clickable. 
I ended up changing the SVG, as something with the svg being used made it not work when we increased the size of the checkboxes.  I also broke it into multilines instead of shorthand, as it's quite long with `url()`
Also changed the spacing between authorize and close buttons

fix(authroize): fixes checkboxes so they display correct

---

package.json
src/components/Layout.js
src/components/Layout.module.css

Reduces the use of tailwind classes, and also removed a div that will no longer be rendered (since there is no service doc)

style: fix styling for when there is no spec

---

src/components/LiveResponse.js
src/components/Parameters.js
src/components/Responses.js
src/helpers/helpers.js
src/index.js
src/styles.css

Overwrite some files to correct their heading levels, as they should not be using `h1` tags.
Also includes fix for TDX-2838, adding `scope` to the table headers to identify table columns, as well as displaying the table header

fix(a11y): adjust heading levels to make more sense (TDX-2840)

---

package.json
src/kongponents.scss
yarn.lock

Updates the kongponents package, as the old one is going to be deprecated. In order for this to work, had to use `sass:map` in order to get the values from the variables. Otherwise, it wouldn't compile properly.

chore: upgrade kongponents styling to 8+ (TDX-2888)

---

package.json
src/styles/_layout.scss
src/styles/main.scss

Fixes the coloring for a border, as well as making sure the select is consistent with other input fields.

style: add some more styles to support dark theme

---

package.json
src/styles/_layout.scss
src/styles/main.scss

- Sets a hardcoded white text as an intermediate fix for the contrast issues on the code snippet widget
- fix some spacing with the `examples-select` select
- remove the pre styling which added random line numbers in the middle of lines of code (e.g. when looking at ruby examples)

style: update styles to address the code snippet widget (TDX-2985)

---

src/components/AugmentingResponses.js
src/helpers/helpers.js

Per https://swagger.io/specification/v3/, the `url` field in server object could be relative. But the `request.url` in har should not be relative.
To fix this, a `toAbsoluteUrl` was added to convert the relative url in spec file to qualified absolute URL
This fix FTI-4899

fix(codesnippet): support relative url in server object

---

package.json

The dist files have a console log that is junk, so this PR bumps package so that we can publish a new package version without this log.

chore: bump version to remove console log

---

package.json
src/components/Layout.module.css
src/styles/_servers.scss

style: fix servers container for consistency (TDX-3204)

---

package.json
src/styles/_servers.scss

Applies theme coloring to the servers text, specifically in the case of dark mode / custom themes.e

style: update servers container text color

---

package.json
src/styles/_layout.scss
src/styles/main.scss

style: wrap flex containers for better response styling

---

package.json
src/styles/main.scss

This fixes the authorize button to display properly

fix: properly display authorize btn (TDX-3426)

---

src/components/Collapse.js
src/components/Models.js
src/components/Operation.js
src/components/ParameterRow.js
src/components/SidebarList.js
src/containers/Filter.js
src/styles.css

the text input auto trim function is not enabled by default, customer who requests this function can manually set `swaggerUIOptions.theme.enableFormInputAutoTrim` to `true` to enable this feature.
this fix FTI-5334

fix: a11y DOM structure improvements and text input auto trim

---

src/components/AugmentingResponses.js

The preview page in KM's portal editor is wrapped in a `<iframe />` and use `srcDoc` to provide content, and `location.href` will be `about:srcdoc` in this situation, leading uncaughted error when executing `new URL('', window.location.href)`
To fix this, we catch the error and use `http://example.com` as fallback base url
This fix FTI-5069

fix: catch `toAbsoluteUrl` in dev portal editor preview

---

package.json
yarn.lock

Bumps the version to fix an issue with some requests returning a response that causes the section for that response to break.

chore: bump swagger2har version

---

src/components/HighlightCode.js
src/components/ParameterRow.js
src/components/custom/ParameterRowError.js

correct the usage of the `tab-index` attribute and enable `errorsDescriedById` support
this fix FTI-5660

fix(a11y): correct tab-index and add aria invalid/describedby support

---

src/components/OperationSummaryPath.jsx
src/index.js

This is so that when hovering, you can see the whole operation tag. This is not semantic HTML in the slightest already, so I didn't see harm in adding some non-standard tags to get the desired behavior.

feat: add custom component for op-summary-path
